### PR TITLE
Fix bad processing javadoc URL

### PR DESCRIPTION
**Pull request by jeremydouglass**
Fixed bad url creating eclipse warnings as per issue #13 

Error message was:
javadoc: warning - Error fetching URL: http://processing.org/reference/javadoc/core/

### CODE REVIEW

**Comment by jeremydouglass** [comment]
@prisonerjohn Is this a live repo? I just realized that it has been almost a year since the last commit / merge.

**Comment by prisonerjohn** [comment]
Yes it is! Thanks for your PRs, I'll look into them soon and merge if it all looks good.

**Comment by jeremydouglass** [comment]
Thanks, glad I sent them to the right place.

I bundled the Java 8 update config update and official stylesheet update into the same PR batch, but really the bad javadoc URL line is the only straight bugfix.

**Review by prisonerjohn — APPROVED** [review]
Thanks!

**Pull request merged**
